### ISSUE TITLE
Calculation of Clearance values, for population created for MoBi project.

### ISSUE THREAD

**Issue by syedmuhammadsharib92** [Open-Systems-Pharmacology/Forum#69] opened 2017-08-30 07:01 UTC
Dear Concerned,
I developed a project to determine pharmacokinetics for cancer drug, I first defined building blocks in PK-Sim and run the simulation.  After simulation, model was exported to MoBi for tumor incorporation.

Again, model was exported from MoBi to PK-Sim to determine population kinetics, I got every parameter, but unable to calculate total body clearance & volume of distribution.

Am i doing some thing incorrect or this is limitation of the software system?

Find the image below for your review. 
![cpt-11 cl](https://user-images.githubusercontent.com/31466223/29859183-47d45d18-8d7a-11e7-8651-f4cee9ed8ef0.PNG)

**Comment by msevestre** [comment] 2017-08-30 11:51
@syedmuhammadsharib92 
This should normally work, provided that the model structure was not change drastically.

Could you attach your PK-Sim project so that I can look at it? Thanks

**Comment by msevestre** [comment] 2017-09-19 00:50
@syedmuhammadsharib92 Any feedback on that? Thanks

**Comment by msevestre** [comment] 2017-10-11 00:03
No feedback in over 3 weeks. Closing. Please reopen at your earliest convenience

**Closed by msevestre** 2017-10-11 00:03 UTC
Labels: question

**Comment by syedmuhammadsharib92** [comment] 2017-10-11 04:36
Dear Michael,

Find attached the PK-Sim file having model imported from MoBi.


As model is imported you can also have a look that none of specific building block can be seen.


Best Regards,

Syed Muhammad Sharib.





Confidentiality is mandatory.

________________________________

**Comment by msevestre** [comment] 2017-10-11 14:18
@syedmuhammadsharib92 
>Confidentiality is mandatory.

Everything posted here is public and thus accessible to everyone.
Luckily attachment via email does not work so your data was not posted.

My suggestion would be that you recreate the problem with some dummy compound and update the file using github.

> As model is imported you can also have a look that none of specific building block can be seen.

This is by design. A MoBi simulation can be anything. Especially its structure may have been changed to add e..g a PD models or other type of extensions. Hence the mapping to PK-Sim building block is not possible.
