### ISSUE TITLE
Reference Concentration change in Binding parameters, but did not update to tissues

### ISSUE THREAD

**Issue by thanghodn** [Open-Systems-Pharmacology/Forum#294] opened 2019-03-16 01:10 UTC
Hi,
 I have a protein binding partner with different expressions in tissues. 
I exported the model to Mobi.
 Now when I go to  that protein binding partner and change the reference concentration under parameter tab, the tissue concentrations still stay unchanged after updated the simulation. Do you have any suggestions to fix this?

**Comment by msevestre** [comment] 2019-03-17 14:49
@thanghodn Would it be possible to put some screenshots or attach a project with steps to reproduce so that I can understand what is not working as expected?

**Comment by thanghodn** [comment] 2019-03-17 16:44
@msevestre I have attached the PDF of the reaction and the steps to build that reaction, and how the results look like. Hopefully, you can help me with this,
[Reaction.pdf](https://github.com/Open-Systems-Pharmacology/Forum/files/2975431/Reaction.pdf)

**Comment by msevestre** [comment] 2019-03-18 02:29
You are changing the reference concentration in the molecule building block...but your simulation is not using the updated building block automatically! You need to perform a building block update in the simulation in order to get the latest reference concentration in your simulation.

Right click on the molecule building block in your simulation and select the  Update action.

Let me know if that helps,

**Comment by thanghodn** [comment] 2019-03-18 04:02
@msevestre I did update the building block, but it did not update the reference concentration.  If I don't update the block, I can see the red exclamation point next under the simulation configuration. The simulation is still the same.

**Comment by msevestre** [comment] 2019-03-18 11:59
Can you attach your project here so that I can take a look? What's the value of the ref concentration parameter in the simulation?

**Comment by thanghodn** [comment] 2019-03-18 16:19
Sure. Please just focus to the CD274, the original reference concentration is 1.58E-10 mol/ml, and want to change it to 1.58E-13 mol/ml. but doesn't look like the simulation update that. 

The model is a little big but please just focus on the CD274 reference concentration.
[CD_072_single_dose_CD274_testing.mbp3.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/2979156/CD_072_single_dose_CD274_testing.mbp3.zip)

**Comment by msevestre** [comment] 2019-03-18 22:46
@thanghodn Ok the reason is that the value in the PSV is not updated
A PSV is a collection of all parameters defined in the individual and the molecule (aside from start values).
In your case, the value is updated in the Molecule BB but not in the PSV
![image](https://user-images.githubusercontent.com/1041237/54568515-d39d9300-49ad-11e9-8310-062549188ec1.png)
If you filter by name like I did, you can see that the value used in the PSV is shown as modified

If you update this value either automatically or manually and then update the simulation, you should be good to go

We have an issue in MoBi (https://github.com/Open-Systems-Pharmacology/MoBi/issues/118) where we discuss how we could improve the behavior of PSV so that not ALL parameters values would be duplicated by default

Hope that helps

**Comment by msevestre** [comment] 2019-03-18 22:47
also please check out the docs on PSV for more info
https://docs.open-systems-pharmacology.org/working-with-mobi/mobi-documentation/model-building-components#parameter-start-values

**Comment by thanghodn** [comment] 2019-03-18 23:27
@msevestre, Thank you! this is ver helpful.
Thang

**Comment by msevestre** [comment] 2019-04-04 15:36
@thanghodn Closing for now. Let us know if you need more help.

**Closed by msevestre** 2019-04-04 15:36 UTC
Labels: answer, help wanted, question
