### ISSUE TITLE
Simulation run failed : some variable became negative

### ISSUE THREAD

**Issue by CHOCHANGKEUN** [Open-Systems-Pharmacology/Forum#311] opened 2019-04-18 06:19 UTC
I have a question about failed simulation

i get a answer about fail simulation that some variables became negative.

the following variable became negative : Organism, Lumen, upperileum 

but, i didn't find parameter where this is. 

please help me, and thank you so much

**Comment by StephanSchaller** [comment] 2019-04-19 12:03
PKSim or MoBi?

try changing your simulation (solver) settings in the simulation (switch to advanced view mode in drop-down at the bottom of the parameter list):
![image](https://user-images.githubusercontent.com/25477643/56423316-cbd25680-62ab-11e9-97ef-6f846a35fa91.png)

Set your tolerances to a lower value.

**Comment by teutonicod** [comment] 2019-04-23 09:04
Hi!
I had the same issue as well a couple of times and also several colleagues experienced the same error. In MoBi and PK-Sim as well. Indeed in some cases this error can be solved by changing the solver settings, but do we have an explanation of why now this issue seems appearing more often? In the past I did never see this error before.

If it can help, I was able to reproduce the error with one of the  MoBi exercises. 

Donato

**Comment by StephanSchaller** [comment] 2019-04-23 09:26
I am not sure the incidence rate of this error has increased.
It strongly depends on the type of processes you are implementing (e.g. biologics with TMDD are more prone to produce this error due to the large differences (multiple orders of magnitude) in concentration levels).

But I believe it could be avoided more often e.g. by providing a guide to e.g. tuning solver settings and setting scale factors.

**Comment by Yuri05** [comment] 2019-04-28 22:36
@CHOCHANGKEUN @teutonicod Can you try to run the problematic simulations with the beta version of PK-Sim 7.5 portable (this will not affect existing OSP-Suite installation)? For this:
* Download [pk-sim-portable-setup.zip](https://ci.appveyor.com/project/open-systems-pharmacology-ci/pk-sim/build/artifacts)
* Unzip downloaded zip-archive and start PKSim.exe

**Comment by teutonicod** [comment] 2019-05-06 12:39
Hi @Yuri05,

The example I have to reproduce the issue is with MoBi, can I use the beta version of MoBi for the test?

**Comment by Yuri05** [comment] 2019-05-06 14:49
@teutonicod yes, you can try MoBi as well
https://ci.appveyor.com/project/open-systems-pharmacology-ci/mobi/branch/develop/artifacts

**Comment by teutonicod** [comment] 2019-05-06 15:01
@Yuri05  Yes, I still have the same error

**Comment by msevestre** [comment] 2019-10-11 00:17
Closing. Please reopen if you need more help

**Closed by msevestre** 2019-10-11 00:17 UTC
