### ISSUE TITLE
Intestinal permeability (transcellular)

### ISSUE THREAD

**Issue by ranamjz** [Open-Systems-Pharmacology/Forum#1181] opened 2022-03-27 11:29 UTC
Dear open systems pharmacology team,
 In order to increase the FA after i get my simulation results i had to adjust the intestinal permeability( transcellular) value and after that i got the fraction absorbed that i expected. But now i am facing 2 problems :
1- which part of the intestine is used in the "intestinal permeability" ?
i myself used the permeability of the large intestine defined in the literature 
2- all the absorbed fractions have become 1 which means that 100% of the medication has been absorbed which is not quite possible

**Comment by Yuri05** [comment] 2022-03-27 17:08
@ranamjz Please do not create duplicate issues and open new discussion topics in the forum under **Discussions**, not under Issues.

**Comment by Yuri05** [comment] 2022-03-27 17:08
Duplicate of #1182

**Closed by Yuri05** 2022-03-27 17:08 UTC
