### ISSUE TITLE
Failure in installation of OSP 7.1.0

### ISSUE THREAD

**Issue by zt1947** [Open-Systems-Pharmacology/Forum#36] opened 2017-07-02 15:15 UTC
I have downloaded OSPSuite-Full.7.1.0 and then installed it.
The Installation Validator did not start automatically and when I tried to start it manually, I have received  error message 1 in the file enclosed.
An attempt to start MoBi resulted in error message 2 in that file.
My Os is: Windows 8.1
I would be grateful for support to overcome these installation issues
[Error messages.docx](https://github.com/Open-Systems-Pharmacology/Forum/files/1117870/Error.messages.docx)

**Comment by msevestre** [comment] 2017-07-02 17:25
@zt1947 
>The Installation Validator did not start automatically

This is the correct behavior. The `Installation Validator` should only start on demand. 

Can you try to restart your computer and see if the error disappear? It seems that some core components cannot be loaded.

If the problem is not solved, can you let us know if the dll `OSPSuite.FuncParser.dll` can be found for example under e.g.  `C:\Program Files\Open Systems Pharmacology\MoBi\7.1` or wherever MoBi is installed?

This is a very peculiar error to say the least

**Comment by zt1947** [comment] 2017-07-03 20:05
Dear Michael
I have downloaded everything from scratch, (after erasing all previous
downloads). The errors were not resolved even after restarting the computer.
 OSPSuite.FuncParser.dll is present in MoBi 7.1, in PK-Sim 7.1 and in
installation Validator 7.1
Looking forward to hear from you.
Zvi

**Comment by msevestre** [comment] 2017-07-03 20:16
@Yuri05 any idea?
@zt1947 did you install 7.0 on this machine? As you can imagine, we install the suite on many OS and windows version as part of our release protocol and we did not have any issue with 7.1

**Comment by msevestre** [comment] 2017-07-04 00:18
@zt1947 Also please make sure that you have all latest update for Windows. We had an issue a few months ago with a PC with outdated service pack.

**Comment by zt1947** [comment] 2017-07-04 04:35
I did have version 7.0 on this machine.
I will make sure as to the most recent updates
Zvi

**Comment by msevestre** [comment] 2017-07-04 12:10
@zt1947 I also presume that you are receiving the same issue when starting PK-Sim?

**Comment by msevestre** [comment] 2017-07-04 13:07
@zt1947 
Can we try the following:

1. Download the file located here http://mobi-portable.open-systems-pharmacology.org/ .This is an experimental portable setup (e.g. no install) from MoBi.
1. The file is a zip file. Please extract the archive somewhere on your machine (your desktop for example)
1. Open the folder MoBi 7.2
1. Start MoBi.exe from there

Let me know if you can start MoBi that way.

This version of MoBi has not been validated nor has been released. This is just a try to understand what's going on on your machine. Please do not use this version for project work

**Comment by zt1947** [comment] 2017-07-04 21:11
Dear Michael
I have started downloading Windows updates.
Seems to be a very long process.
I"ll update you once this is completed and I try again starting MoBi or
PK-Sim
Sincerely
Zvi

**Comment by msevestre** [comment] 2017-07-04 22:23
Ok great. Good luck :)

**Comment by zt1947** [comment] 2017-07-05 05:47
Dear Michael
With all Windows updates downloaded, both PK-Sim & MoBi started OK.
I am now running the Validator and will update you later in the afternoon.
Thanks!
Zvi

**Comment by zt1947** [comment] 2017-07-05 06:11
Dear Michael
It seems that the installation issues on my laptop have been resolved,
however...
I am now trying to install version 7.1.0 on my office table top and new
problems pop up.
Enclosed please find a file with error messages describing the problems
that I and the network's administrator have encountered.
The same eeror messages are received upon an attempt to unisntall older
versions of PK-Sim.
We did check and all of Windows updates have been installed.\
As a;ways, I would be grateful for your assistance.
Sincerely
Zvi

**Comment by Yuri05** [comment] 2017-07-05 07:26
>Enclosed please find a file with error messages describing the problems

Seems the file was not attached..?

**Comment by zt1947** [comment] 2017-07-05 11:14
Here the file is attached again
Zvi

**Comment by msevestre** [comment] 2017-07-05 12:23
@zt1947 attachment only works from within the GitHub platform. Do not attach files via email as they are removed. Thanks

**Comment by zt1947** [comment] 2017-07-09 05:43
Dear Michael
I"ll be away for the next 10 days.
I"ll get back to you, regarding my installation problems, as I return.
I would be gratefull if you could provide an e-mail address to mail the
attachments to.
Thanks for your help
Sincerely
Zvi

**Comment by msevestre** [comment] 2017-07-09 14:41
@zt1947
Support is exclusively via forum. I will close this issue. My suggestion is that you open another entry in the forum upon your return and use the add attachment method (which you have used already with the initial word document). Thanks

**Closed by msevestre** 2017-07-09 14:41 UTC
Labels: answer, help wanted

**Comment by zt1947** [comment] 2017-07-10 06:17
Dear Michael
I have opened a new issue (#42) on the forum.
I did follow the instructions to attach a file, however I am not sure that
anything was attached.
I will deeply appreciate your help
Sincerely
Zvi​
