### ISSUE TITLE
Explanation for a low fraction absorbed (Fa) from duodenum

### ISSUE THREAD

**Issue by RamyAmmar** [Open-Systems-Pharmacology/Forum#179] opened 2018-05-17 09:45 UTC
Dear All,

The figure below shows the fractions absorbed (Fa) of a drug from different GIT segments. As you can see the duodenum shows the lowest Fa. Is there any explanation for this major difference between the Fa from jejunum and ileum, althogh the duodenum has the largest surface area.
 
![image](https://user-images.githubusercontent.com/34481321/40168690-6a8bc74e-59c4-11e8-9670-a7821f43e0eb.png)

This drug is a CYP3A4 substrate so at the beginning I thought that it may be due to the different expression level but the level was the same in duodenum and jejunum.
![image](https://user-images.githubusercontent.com/34481321/40169625-b26c30ba-59c6-11e8-97a2-c1ecffc72342.png)

If there are any publications or explanations that can help, please pass it to me.

Thanks in advance.

**Comment by PavelBal** [comment] 2018-05-17 10:06
Why do you think duodenum has the largest surface area?

![image](https://user-images.githubusercontent.com/25903040/40170763-9c096628-59c9-11e8-8b24-4c34820534f6.png)

Even multiplied by the Effective surface area enhancement factor, the effective surface area of upper jejunum is still greater than that of duodenum.

However, it is interesting that Fa in ileum is also greater than in duodenum. Possible explanations - different transporter expression (Pgp efflux, or some influx transporters?), different solubility of the drug in the respective segments (pH?), formulation (is the drug already completely released in duodenum?). Finally, differences in transit rates could cause higher absorption in e.g. ileum (drug resides longer in ileum).

I would first take a look at the free concentrations of the drug in the lumen segments.

**Comment by RamyAmmar** [comment] 2018-05-17 10:44
@PavelBal Thank you very much for your prompt response.

This is the concentration of the drug in the lumen segments

![image](https://user-images.githubusercontent.com/34481321/40171606-0eaca5d0-59cc-11e8-9095-e90f79b9f877.png)

1. The drug is not a substrate for pgp or other transporters. 
2. The drug is a weak basic and show higher solubility in low pHs (not the case in ileum in comparison to duodenum). 
3. Regarding the release of the drug in the duodenum, I don't know how to show this output in the program, could you show me.
4. Difference in transit time may be the cause.

Is the GIT dimension that you have sent for healthy individual, if so why it shows different values than mine?

![image](https://user-images.githubusercontent.com/34481321/40172608-6aa92770-59cf-11e8-968f-32ea55640315.png)

Could you please send to me the reference based on it these areas and enhancement factors calculated

**Comment by PavelBal** [comment] 2018-05-17 11:14
Sorry for the confusion - I looked at the wrong simulation and showed the surface area values for a mouse. Nevertheless, the relationships are the same, and jejunum still has greater SA than duodenum. I do not know how the values are calculated or where they come from - perhaps this publication can help:

https://jpharmsci.org/article/S0022-3549(15)31824-4/abstract

From your plot I would suspect the formulation being the cause. You can plot the total fraction dissolved over time (there is a respective observer you can choose in PK-Sim), but I don't think there is a built-in way to assess the dissolution in isolated segments. You could try and simulate an immediate release formulation and see how Fa changes.

**Comment by StephanSchaller** [comment] 2018-05-17 11:54
For me, this look pretty consistent (plot on Fa and Concentration in Segments. The amount absorbed in the different segment is roughly speaking defined by:
- Rate of Absorption x Time of residency in Segment.
- Rate of Absorption = Concentration x Surface Area (SA) (+ (if applicable) Active Transport)

What I see: Duodenum has about 1/2 the SA, 1/3 of the concentration and 1/2 of the Time of residency (totalling a fraction of 1/12 amount absorbed) as compared to the Upper Jejunum. This is in line with the 2% vs. 25% Fa you initially reported.

**Comment by StephanSchaller** [comment] 2018-05-17 12:02
Actually: Rate of Absorption = Concentration x Surface Area x *Permeability*

...but Permeability (at default) is the same for all segments.

The Enhancement factor then explains the low Fa for Large Intestine even though concentratuon & time of exposure are high

**Comment by RamyAmmar** [comment] 2018-05-18 14:36
@StephanSchaller Thank you very much for your convenient reply. 
I just have one more question :) How could you explain the low concentration of the drug in the stomach and duodenum although the fraction of dissolved drug is 100% and also the drug concentration in both segments did not reach the saturation levels as in other segments (still more to dissolve).

**Comment by StephanSchaller** [comment] 2018-05-18 17:04
Hm, I guess this is due to the volume of liquid in the respective segments. Liquid volume decreases while it travels along the GI...significantly so once it reaches large intestine...

**Comment by msevestre** [comment] 2018-06-08 18:43
@RamyAmmar Closing. Let us know if you need more help

**Closed by msevestre** 2018-06-08 18:43 UTC
Labels: answer, question
