### ISSUE TITLE
Particle Dissolution

### ISSUE THREAD

**Issue by JanSchlender** [Open-Systems-Pharmacology/Forum#72] opened 2017-09-03 14:25 UTC
The formulation "particle dissolution" seems to be unlinked in a given simulation. Any changes of formulation and respective compound parameters seem to be insensitive. The first screenshot shows a PI result after MC estimation. Although, some parameters were changed, there was no improvement in the overall fit. The second screenshot shows a SA in which the selected parameters showed no sensitivity for the same simulation. 
![grafik](https://user-images.githubusercontent.com/26056951/30003773-2ff810f8-90c3-11e7-8b0b-2cfbb4e6cd87.png)

![grafik](https://user-images.githubusercontent.com/26056951/30003802-d9705442-90c3-11e7-8cf6-2d2f975783a7.png)

**Comment by msevestre** [comment] 2017-09-03 21:39
And I am assuming that you are expecting your  model to be sensitive to those parameters? Is there a way you could attach a project reproducing the behavior? Thanks @JanSchlender

**Comment by Yuri05** [comment] 2017-09-08 09:02
* `Particle radius (XX)` parameters (where _XX_={_min, max, mean, SD_}) are indeed unlinked to the simulation. This is by design. They are used only during _simulation creation_ (**and only in PK-Sim!**) for the estimation of **initial particles distribution** (`Particle radius (at t=0)` and `Number of particles` in each particles bin)
If you would like to change those parameters, you must do it in the corresponding formulation building block and update you simulation (**in PK-Sim only**! In MoBi there is no easy way to do this).

Which also means: `Particle radius (XX)` parameters should never be optimized. (in PK-Sim you cannot even select those parameters for PI; in MoBi it is possible however - which I would consider a bug).

<img width="534" alt="pd" src="https://user-images.githubusercontent.com/25061876/30202701-a8f657a2-947f-11e7-8ac8-c79be5c5a4db.png">

* `Immediately dissolve particles smaller than` parameter might be indeed insensitive in the given range. To check this you should plot the time course of particles radii and compare it with the spatial distribution of the particles within the lumen.

* `Thickness (unstirred water layer)`, `Aqueous diffusion coefficient` and `Density (drug)` should be sensitive and should have influence on your PI outcome. I would need to take a look at your project for more detailed analysis.

**Comment by msevestre** [comment] 2017-09-08 11:20
Agreed with bug in MoBi 
Flag CanBeVaried should be used to filter out parameters

**Comment by JanSchlender** [comment] 2017-09-08 11:35
Regarding the PI of Particle radius in PK-Sim, I performed the attached optimization in PK-Sim. If you mark the Parameter as "Favorite", you can use it in the PI even in PK-Sim.

**Comment by msevestre** [comment] 2017-09-08 11:40
Ah ah nice.

**Comment by Yuri05** [comment] 2017-09-08 11:52
That's a funny :bug:

**Comment by msevestre** [comment] 2017-09-08 12:31
I have creaed this issue for PK-Sim (it will be fixed in MoBi automatically since the implementation is in Core)
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/316

Also I have created
https://github.com/Open-Systems-Pharmacology/MoBi/issues/170

**Comment by JanSchlender** [comment] 2017-09-08 13:01
Tweaked the settings

**Comment by msevestre** [comment] 2017-10-12 12:18
Issues created. Closing

**Closed by msevestre** 2017-10-12 12:18 UTC
Labels: bug, question
