### ISSUE TITLE
MoBi new organ

### ISSUE THREAD

**Issue by watt0005** [Open-Systems-Pharmacology/Forum#98] opened 2017-11-22 13:07 UTC
In the previous version of MoBi, if I wanted to add an organ to the model, I would go through the following process:
1. Click on a similar existing organ and save as .pkml (essentially using it as a template for the new organ)
2. In the tree view, go to Load Container, select the saved .pkml and rename it 
3. Set up neighborhoods, tags, kinetics of mass transfer, etc

Now when I Load Container (e.g., Lung.pkml) and rename it, it not only renames the new organ but also the original (eg Lung) organ.

Is there a way to do this in MoBi 7.1?

**Comment by msevestre** [comment] 2017-11-22 16:40
Hi @watt0005 

I cannot reproduce the problem you are describing

Where are you clicking in the step 2  `In the tree view, go to Load Container, select the saved .pkml and rename it` ?

I have tried with the `bone` organ (as well as the lung organ) and I have now the old bone container and the new one (see screenshot)
![image](https://user-images.githubusercontent.com/1041237/33138959-d7baddf8-cf79-11e7-9534-9b21811d702b.png)

Can you help me reproduce the bug. Maybe there is a step that you are performing that is not mentioned in your description?

Thanks

**Comment by watt0005** [comment] 2017-11-22 16:57
Hi Michael- you are correct – I was not doing exactly what I wrote. When I go to the tree view and right click on Organism and load container, it asks first if I want to rename the container. Once I do that the new organ is added and I can proceed by adding neighborhoods, tags, etc. So problem solved.

Where I had the problem was when I tried to load the container in the Diagram view. When I clicked on Load Container in the upper left corner and loaded a saved .pkml file, it did not ask if I wanted to rename. When I manually right click the new organ and select Rename, I am presented with the following:

[cid:image001.png@01D36389.04F06890]


If I click OK, then both the organs are renamed LungNew

[cid:image002.png@01D36389.04F06890]

So nothing additional needed for me as I can use the first method. But I am curious why the different options depending on the Tree or Diagram view and if it is possible to make this work from the Tree view.

Thanks,
Kevin

Kevin Watt, MD PhD
Assistant Professor of Pediatrics
Duke University Medical Center
Duke Clinical Research Institute
Phone: 919-668-8556
kevin.watt@duke.edu<mailto:kevin.watt@duke.edu>

**Comment by msevestre** [comment] 2017-11-22 17:06
@watt0005 Unfortunately your images are removed when answering via email :(
But I think I get the gist of the problem. Diagram and TreeView SHOULD BEHAVE THE SAME as this is just a different view of the same data. Clearly the Diagram implementation is not correct and this should be changed. I am going to close this issue and create a bug report in the MoBi project

Thanks for the clarification :)

**Comment by msevestre** [comment] 2017-11-22 17:10
@watt0005 I cannot reproduce the issue in the diagram either... Could you add those screenshots via Github after all :)

**Comment by watt0005** [comment] 2017-11-22 17:13
![neworgan1](https://user-images.githubusercontent.com/31321213/33140616-81623a8c-cf7e-11e7-9bf6-233fd762de7a.png)
![neworgan2](https://user-images.githubusercontent.com/31321213/33140620-85b1c09e-cf7e-11e7-8bed-f8ed76f422e6.jpg)

**Comment by msevestre** [comment] 2017-11-22 17:25
@watt0005 Interesting
I am wondering how you managed to add another organ with the name Lung. I tried the same workflow and MoBi asks me to rename the Lung organ

![image](https://user-images.githubusercontent.com/1041237/33141099-16a6076c-cf80-11e7-8be0-07702f70a54d.png)


and then after rename
![image](https://user-images.githubusercontent.com/1041237/33141120-2ad0e6da-cf80-11e7-8915-26ad922c1f8a.png)

So there is a bug... but hard to reproduce :(

**Comment by Christoph27** [comment] 2017-11-22 17:42
By the way: Be aware that lung is a special organ (e.g. blood flow is an equation summing up the blood flow of all other organs) . Depending on what you want to do, you might consider using a "normal" organ e.g. gonads or heart as template.  
I had not the Problems described with naming (as Michael described, MoBi asks me to re-name and after that only the new organ has the new name ...)

**Comment by watt0005** [comment] 2017-11-22 17:43
Interesting. I just reproduced. Exact steps were:

1. Export simulation from PK Sim to MoBi
2. Open the Spatial Structure
3. Click Load under the Add group in the top left corner
4. Select Lung.pkml
5. I am then prompted to rename the different neighborhoods (eg Lung_pls_Lung_int) but not asked to rename the organ

**Comment by Christoph27** [comment] 2017-11-22 18:16
I don't understand the 3. step: "under the Add group in the top left corner"

The steps which work in my example:
0. Simulation exported to MoBi
1. In the spatial structure: save an organ as pkml (e.g. heart)
2. In the spatial structure: at Organism level (tree or diagram view) -> right click -> load container -> select pkml file
3. A window pops up asking to "select containers to load" -> select top container i.e. in this case "heart"
4. A window pops up asking you to rename the container. -> Rename 
5. After that,  rename the neighbourhoods accordingly in the windows pooping up successively.

**Comment by watt0005** [comment] 2017-11-22 18:19
When on the Diagram screen, I am not right-clicking to load container. I am clicking the Load button in the screen shot below:
![image](https://user-images.githubusercontent.com/31321213/33143367-ae0e88e8-cf87-11e7-86aa-376ff0f805f2.png)

**Comment by msevestre** [comment] 2017-11-22 18:54
Ah ah. Thanks @watt0005 . This was the missing piece

**Comment by msevestre** [comment] 2017-11-23 13:36
I created an [issue](https://github.com/Open-Systems-Pharmacology/MoBi/issues/207) for MoBi. Thanks @watt0005

**Closed by msevestre** 2017-11-23 13:36 UTC
Labels: question
