### ISSUE TITLE
Competitive inhibition of Hill kinetic active transport not working 

### ISSUE THREAD

**Issue by NinaHanke** [Open-Systems-Pharmacology/Forum#351] opened 2019-06-24 14:04 UTC
Dear masters of PK-Sim and MoBi, 

I tried to add a competitive inhibition to a transporter with a Hill kinetic (Hill coefficient = 3.0). 
Nothing happened... (if I change transporter Km, -kcat or -concentration, I see the effect). 

When I export to MoBi, there is no Km_app, although I have the competitive inhibition configured in PK-Sim, before exporting to MoBi (see picture on the left). 
When I change this transporter to a normal Michaelis-Menten active transport with competitive inhibition, everything is fine in my MoBi file, (see picture on the right). 

![grafik](https://user-images.githubusercontent.com/36850897/60025152-5a42ca00-9699-11e9-822a-c0e2d3d8ad2a.png)

Trying to add Km_app in MoBi did not work, because he did not like the paths I added for K_water1 and KcI1, even when I copied them from the working MoBi file (SOURCE|Perpetrator|Partition coefficient (water/container) and SOURCE|Perpetrator|Concentration) to build the 
Km interaction factor = 1 + K_water1*Ic1/KcI1. 

Is this a known problem, or did I make a mistake? 

Please help :) 
Cheers, 
Nina

**Comment by Yuri05** [comment] 2019-06-26 16:21
>Is this a known problem, or did I make a mistake?

It's a feature 😄 
Combination `{DDI+Hill kinetics}` is deactivated **by design**.
Simply due to the fact that we did not invest time into developing the [common DDI formulas](https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-compounds-defining-inhibition-induction-processes#multiple-inhibitors-equations-used-by-pk-sim-r) for the Hill kinetics.
Everybody who could invest time into developing those formulas for Hill is welcome 😉 

S. also: https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1283

@sfrechen @TWendl FYI

**Comment by NinaHanke** [comment] 2019-06-26 16:39
Ok, many thanks Juri!!!!! 

Then I will try a work-around via Km. 
And next time maybe resist the urge to implement cooperativity :confused:

**Comment by sfrechen** [comment] 2019-07-01 16:24
@NinaHanke 
For which transporter is cooperativity described?
How would you like to implement competitive inhibition in such a case? Which model do you want to apply?

**Comment by NinaHanke** [comment] 2019-07-01 16:37
Its for PMAT, a transporter involved in metformin absorption. 
https://www.ncbi.nlm.nih.gov/pubmed/17600084

I wanted to see how the metformin DDI looks like, if I add competitive inhibition of PMAT (no experimental data available, just hypothesis testing). 

Not sure how to build it in though, as I could not find any formulas in literature, yet. 
I would probably just change the Km, as always with competitive inhibition, as a first guess.

**Comment by msevestre** [comment] 2019-10-11 00:06
Closing. Please reopen if you need more help

**Closed by msevestre** 2019-10-11 00:06 UTC
Labels: answer, question
