### ISSUE TITLE
Simulated time profile doesn't match time profile from parameter identification

### ISSUE THREAD

**Issue by miluez** [Open-Systems-Pharmacology/Forum#187] opened 2018-06-05 20:35 UTC
I am simulating a plasma concentration-time curve for a molecule that has transporter contribution but am having trouble with the optimization of Km and Vmax.

1) I use initial estimates for transporter Km and Vmax in my simulation, based on the literature.
![1](https://user-images.githubusercontent.com/29264403/41001172-360939ec-68de-11e8-8269-f6dcdeb6d0eb.jpg)

2) I use this simulation in parameter identification to optimize Km and Vmax. From this, I obtain a new concentration-time profile, and optimized Km and Vmax values.
![2](https://user-images.githubusercontent.com/29264403/41001174-38f1b562-68de-11e8-9e2b-44c551242b98.jpg)

3) I have tried transferring the optimized values manually to the first simulation and using the transfer function, double checking the units. However, there is no change to the simulated concentration-time profile. I even changed the Km and Vmax values to ridiculously high or low values and there is no impact on the model.
I have also tried creating a new simulation (not from cloning) and using a new compound block with the updated Km and Vmax values. The new simulation looks exactly like the first one, pre-parameter optimization.
EDIT: The reaction diagram appears to be blank despite setting the transport parameters to the corresponding protein.

Am I misunderstanding the parameter estimation output and how to use it?

**Comment by msevestre** [comment] 2018-06-05 23:01
@miluez This is exactly how the parameter identification is supposed to work. Upon completion, you should be able to transfer the optimal parameters to the simulations and the results after simulation should be identical. 

Would you be able to attach your project so that we can take a look and see if we can understand the issue that you have? 

Thanks,
Michael

**Comment by miluez** [comment] 2018-06-06 03:26
Hi Michael,

Thanks for responding so quickly. I have attached the project file here:

[parameter identification.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/2074688/parameter.identification.zip)

**Comment by miluez** [comment] 2018-06-06 15:31
Hi Michael,

Thank you so much for taking the time to address this. Yes, I previously changed it in the compound building block, then ran a new simulation using the updated building block. I think perhaps I am not clear on when something needs to be changed in the simulation itself (under parameters tab) vs the building block.

**Comment by StephanSchaller** [comment] 2018-06-06 15:36
Maybe some additional thoughts (without looking at the project file):

It looks like you are having an oral administration/absorption and quite some deviation for Cmax of Simulation vs. Observation.
Have you considered fitting other parameters instead of Km and Vmax? Maybe solubility, gastric emptying or intestinal permeability are another option, at least as an exploration.

And to be sure: have you double checked dimensions when importing the observed data. The deviations may also be caused by selecting a wrong dimension upon import (which is then recalculated to the dimension of you simulation output).

Best,
Stephan

**Comment by msevestre** [comment] 2018-06-06 15:37
@miluez The idea of the building block is that it serves as a template to create a bunch of simulations etc..
When you change a parameter in the building block however, it does not update ALL Simulations automatically. Instead the simulation shows that something has change. You can decide then to update your simulation with the new building block (this is the Update) or Commit your changes in the simulation back to the building block (Commit)

![image](https://user-images.githubusercontent.com/1041237/41048925-cd2cb228-697d-11e8-85e1-71ebe119ac7f.png)

The RED icon is your clue that something has changed. You can right click on the element and click Show Differences to actually see the difference. 

![image](https://user-images.githubusercontent.com/1041237/41048987-e9751a4c-697d-11e8-9d41-485308ac8985.png)

Hope that helps,

**Comment by msevestre** [comment] 2018-06-08 18:43
@miluez Closing. Let us know if you need more help

**Closed** 2018-07-21 08:20 UTC
Labels: answer, question
